### ISSUE TITLE
Invalid option "api_key" during Deploy

### ISSUE THREAD

**Issue by SavanDev** [kevinta893/unity3d-travis-ci#5]
During the deploy I receive this message.
>invalid option "--api_key="
failed to deploy

Is something of $GITHUB_TOKEN?
Because I don't see that it's initialized in the code.

**Comment by kevinta893** [comment]
Can I see your Build Log?

$GITHUB_TOKEN is a token used to authorize Travis-CI to access your Github Repository and if permissions allow, also allow it to deploy into your repository's Releases. You need to set this up in your Travis-CI account as a secret environment variable. 

See Deployment: https://docs.travis-ci.com/user/deployment/pages/
About _Secret_ Environment variables: https://docs.travis-ci.com/user/environment-variables#defining-variables-in-repository-settings

**Comment by SavanDev** [comment]
Thanks, now it's works. 😄

The Build Log:
https://travis-ci.org/SavanDev/unity3d-travis-ci
