### ISSUE TITLE
Cannot build target: Failed to active/update license. Missing or bad username and password.

### ISSUE THREAD

**Issue by MixieVR** [kevinta893/unity3d-travis-ci#6]
Hi there! First of all, thanks for making this repo public it helps a lot.

When I update the links to version 2019.1 then I get the following error:

`Cancelling DisplayDialog: Failed to activate/update license. Missing or bad username and password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode.`

I guess this means that this method is no longer possible since Unity now requires a license?

Was wondering if you have any thoughts on this.

**Comment by kevinta893** [comment]
Have you tried to add in your Username and Password using the `-username` and `-password` flags? Remember to set them using _secret_ environment variables via Travis CI.

See the command line reference: https://docs.unity3d.com/Manual/CommandLineArguments.html

Unfortunately as newer versions of Unity are released, the licensing requirements may change and may eventually be closed off completely from Travis CI or other CI platforms. 

Let me know if this works and if not I might look into the problem deeper.

**Comment by Austin47** [comment]
I actually had this exact issue, and for me, I needed the email, password and serial key.
If you don't have Unity plus or higher, you might not be able to launch unity using the command line. At least not in a remote server. (to my knowledge) also [See this](https://forum.unity.com/threads/5-4-0p1-fails-to-launch-due-to-license.425277/).

But if you do have a plus account, you should be fine. Also, I would advise from having your email, password and serial key in your git repository, especially if its public. Travis CI has a way to add encrypted environment variables. [See guide](https://docs.travis-ci.com/user/encryption-keys/)

Here's an example of how this looks:

```
/Applications/Unity/Unity.app/Contents/MacOS/Unity \
  --args buildName $UNITY_BUILD_APK_NAME \
  -batchmode \
  -nographics \
  -silent-crashes \
  -logFile \
  -projectPath "$PROJECT_PATH" \
  -buildTarget "Android" \
  -username "$UNITYEMAIL" \
  -password "$UNITYPASSWORD" \
  -serial "$UNITYKEY" \
  -executeMethod "Infrastructure.EditorHelpers.Builder.BuildDevForAndroid" |
  tee "$LOG_FILE"
```

[See full script](https://github.com/Austin47/ProjectPhotoAR_UnityClient/blob/master/travis-build/build.sh)

Small note, I've noticed that I can only use two machines per key, so at the end of the build process, I need to make sure to return the key from the virtual machine. 

```
echo "return license"
/Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -returnlicense
```

[See full script](https://github.com/Austin47/ProjectPhotoAR_UnityClient/blob/master/travis-build/clean-up.sh)

A little late, but I hope this helps.

**Comment by SimonVie** [comment]
> I actually had this exact issue, and for me, I needed the email, password and serial key. If you don't have Unity plus or higher, you might not be able to launch unity using the command line. At least not in a remote server. (to my knowledge) also [See this](https://forum.unity.com/threads/5-4-0p1-fails-to-launch-due-to-license.425277/).
> 
> But if you do have a plus account, you should be fine. Also, I would advise from having your email, password and serial key in your git repository, especially if its public. Travis CI has a way to add encrypted environment variables. [See guide](https://docs.travis-ci.com/user/encryption-keys/)
> 
> Here's an example of how this looks:
> 
> ```
> /Applications/Unity/Unity.app/Contents/MacOS/Unity \
>   --args buildName $UNITY_BUILD_APK_NAME \
>   -batchmode \
>   -nographics \
>   -silent-crashes \
>   -logFile \
>   -projectPath "$PROJECT_PATH" \
>   -buildTarget "Android" \
>   -username "$UNITYEMAIL" \
>   -password "$UNITYPASSWORD" \
>   -serial "$UNITYKEY" \
>   -executeMethod "Infrastructure.EditorHelpers.Builder.BuildDevForAndroid" |
>   tee "$LOG_FILE"
> ```
> 
> [See full script](https://github.com/Austin47/ProjectPhotoAR_UnityClient/blob/master/travis-build/build.sh)
> 
> Small note, I've noticed that I can only use two machines per key, so at the end of the build process, I need to make sure to return the key from the virtual machine.
> 
> ```
> echo "return license"
> /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -batchmode -returnlicense
> ```
> 
> [See full script](https://github.com/Austin47/ProjectPhotoAR_UnityClient/blob/master/travis-build/clean-up.sh)
> 
> A little late, but I hope this helps.

This works perfectly. I took my bash script. Added Username, password and serialkey as gitlab ci variables to the unity cli call.
Thank you so much :)
